/**
 * SVG Components Index
 * Generated by svger-cli
 * 
 * Import individual components:
 * import { Basic } from './components';
 * 
 * Import all components:
 * import * as Icons from './components';
 */

export { default as Basic } from './Basic';
export { default as Styled } from './Styled';
